"""add_node_id_to_quiz_attempts

Revision ID: 340e2ebf056a
Revises: cc4c16f950b1
Create Date: 2026-02-08 17:02:20.161832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340e2ebf056a'
down_revision: Union[str, None] = 'cc4c16f950b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_activities', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('node_contents', 'question_key',
               existing_type=sa.TEXT(),
               comment='Hash key to distinguish different questions for same node. NULL for knowledge_card (one per node), sha256[:16] of question text for clarification/qa_detail.',
               existing_comment='Hash key to distinguish different questions for same node. NULL for knowledge_card, sha256[:16] of question text for clarification/qa_detail.',
               existing_nullable=True)
    op.drop_index(op.f('idx_profiles_active_course'), table_name='profiles')
    op.drop_index(op.f('idx_profiles_last_accessed_course'), table_name='profiles')
    op.add_column('quiz_attempts', sa.Column('node_id', sa.Integer(), nullable=False, comment='Which node (quiz node) this attempt belongs to'))
    op.create_index('idx_quiz_attempts_course_map_node', 'quiz_attempts', ['course_map_id', 'node_id'], unique=False)
    op.create_index('idx_quiz_attempts_node_id', 'quiz_attempts', ['node_id'], unique=False)
    op.alter_column('user_stats', 'mastered_nodes_count',
               existing_type=sa.INTEGER(),
               comment='已掌握节点数（已完成的节点数）',
               existing_comment='已掌握节点数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_table_comment(
        'user_stats',
        existing_comment='用户学习统计数据表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'user_stats',
        '用户学习统计数据表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('user_stats', 'mastered_nodes_count',
               existing_type=sa.INTEGER(),
               comment='已掌握节点数',
               existing_comment='已掌握节点数（已完成的节点数）',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_quiz_attempts_node_id', table_name='quiz_attempts')
    op.drop_index('idx_quiz_attempts_course_map_node', table_name='quiz_attempts')
    op.drop_column('quiz_attempts', 'node_id')
    op.create_index(op.f('idx_profiles_last_accessed_course'), 'profiles', ['last_accessed_course_map_id'], unique=False)
    op.create_index(op.f('idx_profiles_active_course'), 'profiles', ['active_course_map_id'], unique=False)
    op.alter_column('node_contents', 'question_key',
               existing_type=sa.TEXT(),
               comment='Hash key to distinguish different questions for same node. NULL for knowledge_card, sha256[:16] of question text for clarification/qa_detail.',
               existing_comment='Hash key to distinguish different questions for same node. NULL for knowledge_card (one per node), sha256[:16] of question text for clarification/qa_detail.',
               existing_nullable=True)
    op.alter_column('learning_activities', 'id',
               existing_type=sa.UUID(),
               comment='Primary key',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###
