"""Initial tables

Revision ID: a6385fb425cf
Revises: c2e37946229a
Create Date: 2026-02-01 00:55:15.090278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6385fb425cf'
down_revision: Union[str, None] = 'c2e37946229a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.Text(), nullable=False, comment='exploration | calibration_r1 | calibration_r2 | focus | source | handoff'),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('level', sa.Text(), nullable=True, comment='Novice | Beginner | Intermediate | Advanced'),
    sa.Column('verified_concept', sa.Text(), nullable=True),
    sa.Column('focus', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('intent', sa.Text(), nullable=True, comment='add_info | change_topic'),
    sa.Column('state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full internal state snapshot'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_onboarding_phase', 'onboarding_sessions', ['phase'], unique=False)
    op.create_index('idx_onboarding_topic', 'onboarding_sessions', ['topic'], unique=False)
    op.create_table('prompt_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('prompt_name', sa.Text(), nullable=False),
    sa.Column('prompt_hash', sa.Text(), nullable=False, comment='sha256 hex of prompt text'),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True, comment='Optionally truncated response text'),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('idx_prompt_runs_created_at', 'prompt_runs', ['created_at'], unique=False)
    op.create_index('idx_prompt_runs_prompt_hash', 'prompt_runs', ['prompt_hash'], unique=False)
    op.create_index('idx_prompt_runs_prompt_name', 'prompt_runs', ['prompt_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prompt_runs_prompt_name', table_name='prompt_runs')
    op.drop_index('idx_prompt_runs_prompt_hash', table_name='prompt_runs')
    op.drop_index('idx_prompt_runs_created_at', table_name='prompt_runs')
    op.drop_table('prompt_runs')
    op.drop_index('idx_onboarding_topic', table_name='onboarding_sessions')
    op.drop_index('idx_onboarding_phase', table_name='onboarding_sessions')
    op.drop_table('onboarding_sessions')
    # ### end Alembic commands ###
